### ISSUE TITLE
Help for vercel deployment

### ISSUE THREAD

**Issue by DevShubX** [Isoaxe/cors-server#8]
I want to ask about how to deploy this in vercel. because i have deployed it in vercel but whenever i request some url it give me the cors error 'access-control' error. please help

**Comment by isoaxe** [comment]
Is there a reason why you need to deploy with Vercel rather than using one of the tested methods that definitely work? I would recommend using `fly.io` instead. I haven't used `cors-server` with Vercel before so can't be sure what the issues might be.

Give me more information on the API request that you're trying to make and I'll take a look. Try to be as detailed and clear as possible. Also provide the URL of your version of `cors-server` on Vercel.

**Comment by DevShubX** [comment]
Thanks for the reply, but i research and find out that if we try any type of proxy in vercel it will lead to suspension of our account, and it will try other service as you stated
